apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: system
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/two-first-names/apps.git
    targetRevision: HEAD
    path: system/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd