apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: concourse
  namespace: argocd
spec:
  project: system
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
  source:
    chart: concourse
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 1.3.6
    helm:
      parameters:
      - name: service.type
        value: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: concourse