apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: concourse
  namespace: argocd
spec:
  project: system
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
  source:
    path: system/concourse
    repoURL: https://github.com/two-first-names/apps.git
  destination:
    server: https://kubernetes.default.svc
    namespace: concourse  