apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  project: system
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
  source:
    chart: keycloak
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 9.2.0
    helm:
      parameters:
      - name: service.type
        value: ClusterIP
      - name: auth.createAdminUser
        value: false
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak