apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: system
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.2.4
    helm:
      parameters:
      - name: defaultSettings.defaultReplicaCount
        value: "1"
      - name: defaultSettings.createDefaultDiskLabeledNodes
        value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system