apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: optimalverse-mediawiki
  namespace: argocd
spec:
  project: optimalverse
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mediawiki
    targetRevision: 14.0.1
    helm:
      parameters:
      - name: mediawikiUser
        value: admin
      - name: mediawikiPassword
        value: admin
      - name: mediawikiEmail
        value: savant@optimalver.se
      - name: mediawikiName
        value: Optimalverse
      - name: mediawikiHost
        value: wiki.optimalver.se
      - name: mariadb.auth.password
        value: optimalverse
  destination:
    server: https://kubernetes.default.svc
    namespace: optimalverse-mediawiki