apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd.twofirstnames.org

  users.anonymous.enabled: "true"  
  
  oidc.config: |
    name: Keycloak
    issuer: https://keycloak.twofirstnames.org/realms/login
    clientID: argocd
    clientSecret: $oidc.keycloak.clientSecret
    requestedScopes: ["openid", "profile", "email", "groups"]