apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd.twofirstnames.org

  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: 22cf8c716f64dd7d3cf6 
        clientSecret: $argocd-github:client-secret