apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=stable
- argocd-cm.yaml
- argocd-server-tls.json
- projects/system.yaml
- argocd-github.json