apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/argoproj/argo-cd/manifests/cluster-install?ref=stable
- argocd-server-tls.json
- argocd-github.json
- argocd-keycloak.json
- projects/system.yaml
- projects/twofirstnames.yaml
- projects/optimalverse.yaml

patches:
- argocd-cm.yaml
- argocd-rbac-cm.yaml