apiVersion: v1
kind: ConfigMap
metadata:
  name: prosody-config 
data:
  admin.conf.cfg.lua: |
    admins = { "omega@twofirstnames.org" }
  twofirstnames.org.vhost.cfg.lua: |
    VirtualHost "twofirstnames.org"
  twofirstnames.org.cmpt.cfg.lua: |
    Component "conference.twofirstnames.org" "muc"

    Component "pubsub.twofirstnames.org" "pubsub"
  optimalver.se.vhost.cfg.lua: |
    VirtualHost "optimalver.se"

    admins = { "omega@optimalver.se" }
    allow_registration = true
  optimalver.se.cmpt.cfg.lua: |
    Component "conference.optimalver.se" "muc"

    Component "pubsub.optimalver.se" "pubsub"