apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cloudflare-api-token-secret.json
- issuer.yaml
- certificate.yaml
- github.com/two-first-names/kustomize/prosody?ref=9595cb60b2ed0bbec51717ced3f1e92d1d0ae3e4

patches:
- configmap.yaml