apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cloudflare-api-token-secret.json
- issuer.yaml
- certificate.yaml
- github.com/two-first-names/kustomize/prosody?ref=e594e2a5ae4c034b8870371a7b451afd1c069190

patches:  
- configmap.yaml