apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cloudflare-api-token-secret.json
- issuer.yaml
- certificate.yaml
- github.com/two-first-names/kustomize/prosody?ref=ceeb2f02507818ae2f6705b1dada52bf705d88da

patches:  
- configmap.yaml